### ISSUE TITLE
Parameter declaration in setVersion not compatible in finding API

### ISSUE THREAD

**Issue by GuidoLeibbrand** [michabbb/php-ebay-sdk#1]
In PHP8 i get an error when trying to set the version number

```
$finding = new macropage\ebaysdk\finding\finding();
$finding->setVersion('1.13.0');
```

**Error message:**

```
Fatal error: Uncaught TypeError: macropage\ebaysdk\base\base::setVersion(): Argument #1 ($version) must be of type int, string given, called in /opt/project/inc/ebay/ebay_new.php on line 163 and defined in /opt/project/vendor/macropage/php-ebay-sdk/base.php:93
Stack trace:
#0 /opt/project/inc/ebay/ebay_new.php(163): macropage\ebaysdk\base\base->setVersion('1.13.0')
#1 /opt/project/inc/containerManager.php(121): exporter\ebay\Ebay->__construct(Object(Pimple\Container), 2)
#2 /opt/project/vendor/pimple/pimple/src/Pimple/Container.php(122): ContainerManager::{closure}(Object(Pimple\Container))
#3 /opt/project/mode/jobber/test/ebay_getstore.php(25): Pimple\Container->offsetGet('EBAY2')
#4 /opt/project/mode/Mode.php(113): Mode_test_ebay_getstore->ebay_getstore()
#5 /opt/project/mode/Mode.php(54): Mode->dojob()
#6 /opt/project/exporter.php(269): Mode->do_your_sub_job(Array)
#7 {main}
  thrown in /opt/project/vendor/macropage/php-ebay-sdk/base.php on line 93
```

**Reson:**

base.php Line 93

    public function setVersion(int $version): void
    {
        $this->version = $version;
    }

**Possible solution (use union types):**

```     
public function setVersion(int|string $version): void
{
     $this->version = $version;
}
```

**Comment by michabbb** [comment]
which branch are you using?

**Comment by GuidoLeibbrand** [comment]
The problem exists in php7 and php8 branches.

**Comment by michabbb** [comment]
inside ebay, the "version" is a string anyway, so it makes no sense at all using "int" here. thanks for pointing that out.
